// Regular Expression : is a pattern for string matching/manipulation!

// million of lines of text: "keyin", How many times?
// colou?r: This is a regular expression that matches both color & colour...8000 times..(1500 times ... colour or 2500 times it was color... Color, cOlour.. /colou?r/ig)

// A regular expression comes under /colou?r / ..
// . means literally any character....
// [] refer to a group of letters, either of them is accepted...
// the ^ inside square box makes the reverse... [^sa] .. ANYTHING BUT sa.....
// \d... represents a digit in re...
// \D.. represents anything BUT a digit..
// \s .. represents a space
// \w .. represens a word containing [a-zA-Z0-9_]
// \W.. means anything BUT a word..
// ?... makes a letter optional...
// ( ) it has a literall meaning.. "Capture Group"
// * means 0 or more occurances of something...
// + means 1 or more occurances of something...

// {} refer to the exact number of digits.. /\d{3}/... {2,5} between 2 to 5... {4, } minimum 4 .. maxiumum any number 4 or more....

// (\(?\d{3}\)?\s*)?\d{3}\s*\d{4}
// ^ is the beginning of the string... $ is the ending of the string...
// SPecial functions that use REs to carryout a lot of useful tasks...
// .test(), match() , replace()/replaceAll(), split()
